name: Prepare a new release

on:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: index.js
