name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --ignore-scripts
      - run: pnpm run lint
      - run: pnpm run build
#      - run: pnpm run test  # size.yml takes care of the only test we have for now
